### ISSUE TITLE
Different CIs compared to those in the [correction](http://pubs.acs.org/doi/abs/10.1021/es60140a017) 

### ISSUE THREAD

**Issue by ghost** [brsr/tsk#2]
According to the correction, the 0,5,10,20% trimmed TSK CI for dataset 1c in Table II is (39.14, 44.49), (39.86, 45.38), (39.51, 46.34) and (40.77, 45.17). However, the tsk package give results as following, (39.19, 44.44), (39.91, 45.32), (39.57, 46.26), and (40.81, 45.12). They are all very close but not identical or with negligible differences. Is there an explanation for this?

**Comment by brsr** [comment]
By default, tsk uses a confidence level of 95%. Hamilton et al's paper uses a confidence level of exactly two standard deviations, which is `2*pnorm(2)-1` = 95.44997%. It seems like this was a common approximation back in the dark ages of computing.

Compare:

    > data(hamilton)
    > p <- 2*pnorm(2)-1
    > tsk(hamilton$dr1c)
    [...]
    $conf.int
    [1] 39.18761 44.43632
    [...]
    > tsk(hamilton$dr1c, conf.level=p)
    [...] 
    $conf.int
    [1] 39.13734 44.49340
    [...]

The "tests" directory contains all of Hamilton's data, and it matches within rounding, as long as you use  a confidence level of 95.44997%.

**Comment by ghost** [comment]
@brsr , thank you very much! I was so confused in the past two days but didn't really checked the paper itself.
